server:
  port: 8080

spring:
datasource:
  driverClassName: com.mysql.jdbc.Driver
  url : jdbc:mysql://localhost:3306/marketplace_db?useSSL=false&serverTimezone=UTC
  username : root
  password : 14807419
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    default-serialization-format: application/json
    history-level: full  # Full history, change as needed for production
